/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.gui;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.Socket;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author mitch
 */ 
public class loginFrame extends javax.swing.JFrame {
    static int DAYTIME_PORT = 2001;
    static mainFrame mf = new mainFrame();
    static loginFrame lf = new loginFrame();
    static JTextField tf = new JTextField();
    static JTextArea textArea = new JTextArea();
    /**
     * Creates new form UI
     */
    public loginFrame() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usernameTf = new javax.swing.JTextField();
        passwordTf = new javax.swing.JTextField();
        registerBtn = new javax.swing.JButton();
        loginBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Title.setText("Easy Budget");

        jLabel1.setText("Username:");

        jLabel2.setText("Password:");

        registerBtn.setText("Register");
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });

        loginBtn.setText("Login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(registerBtn)
                        .addGap(18, 18, 18)
                        .addComponent(loginBtn)
                        .addGap(0, 86, Short.MAX_VALUE))
                    .addComponent(usernameTf)
                    .addComponent(passwordTf))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Title)
                .addGap(147, 147, 147))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(Title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(usernameTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(passwordTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerBtn)
                    .addComponent(loginBtn))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        String username = usernameTf.getText();
        String password = passwordTf.getText();
        
        try {
            String host = "127.0.0.1";


            Socket sock = new Socket( host, DAYTIME_PORT );

            BufferedReader in =
                new BufferedReader(
                    new InputStreamReader( sock.getInputStream() ) );

            PrintWriter out =
            new PrintWriter( sock.getOutputStream(), true );
            
            out.println("REG");
            String response = in.readLine();

            if(response.equals("OK")){
               out.println(username);
               out.println(password);
               String error = in.readLine();
               if(error.equals("1"))
                   JOptionPane.showMessageDialog(this, "You need to create a password");
               else if(error.equals("2"))
                   JOptionPane.showMessageDialog(this, "That username is already taken");
               else{
                   JOptionPane.showMessageDialog(this, username + " is now registered.");  
               }
            }
        }
        catch ( IOException e ) {
            System.err.println("IOEXCEPTION");
            System.err.println( e.getMessage() );
        }
    }//GEN-LAST:event_registerBtnActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        String username = usernameTf.getText();
        String password = passwordTf.getText();
        
        try {
            String host = "127.0.0.1";


            Socket sock = new Socket( host, DAYTIME_PORT );

            BufferedReader in =
                new BufferedReader(
                    new InputStreamReader( sock.getInputStream() ) );

            PrintWriter out =
            new PrintWriter( sock.getOutputStream(), true );
            
            out.println("LOGIN");
            String response = in.readLine();
            
            if(response.equals("OK")){
                out.println(username);
                out.println(password);
                String check = in.readLine();
                if(check.equals("1")){
                    JOptionPane.showMessageDialog(this, "That username is not "
                            + "registered yet.");
                }
                else if(check.equals("2")){
                    JOptionPane.showMessageDialog(this, "The password/username combination"
                            + "is incorrect.");
                }
                else if(check.equals("3")){
                    JOptionPane.showMessageDialog(this, "That user is already logged on");
                }
                else{
                    String total = in.readLine();
                    int totalAmount = Integer.parseInt(total);
                    if(totalAmount == 0){
                            dispose();
                            mf.setVisible(true);
                    }
                    else{
                        for(int i = 0; i < totalAmount; i++){
                            String category = in.readLine(); 
                            System.out.println("The category is " + category);
                            mf.categoryText.setText(category);
                            mf.addCategoryBtn.doClick();
                            mf.categoryText.setText("");
                        }
                        dispose();
                        mf.setVisible(true);
                             
                            
                    }
                }
            }
        }
        catch ( IOException e ) {
            System.err.println("IOEXCEPTION");
            System.err.println( e.getMessage() );
        }
    }//GEN-LAST:event_loginBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton loginBtn;
    private javax.swing.JTextField passwordTf;
    private javax.swing.JButton registerBtn;
    public static javax.swing.JTextField usernameTf;
    // End of variables declaration//GEN-END:variables
}
